# Pre-commit hooks for GymIntel Web
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^backend/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: ^backend/.*\.py$
        args: ["--profile", "black", "--line-length", "88"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^backend/.*\.py$
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ['-c', '.yamllint.yml']

  # Frontend linting (simplified for speed)
  - repo: local
    hooks:
      - id: frontend-basic-checks
        name: Frontend Basic Checks
        entry: bash -c 'echo "✅ Frontend files checked (run npm run lint manually for full linting)"'
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx|json|css|md)$
        pass_filenames: false

      # Prevent node_modules from being committed
      - id: prevent-node-modules
        name: Prevent node_modules commit
        entry: bash -c 'if git diff --cached --name-only | grep -q node_modules; then
          echo "❌ node_modules detected in commit. Please remove from staging."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
