# YAML Linting Configuration
extends: default

rules:
  line-length:
    max: 250
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
