version: '3.8'

services:
  test-db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER:-gymintel_test}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD:-gymintel_test}
      POSTGRES_DB: ${TEST_DATABASE_NAME:-test_gymintel}
    ports:
      - "5432:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data:
