[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"]

[phases.install]
cmds = [
    "ls -la",
    "ls -la backend/",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python3 backend/start.py"

[variables]
PYTHONUNBUFFERED = "1"
