[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"]

[phases.install]
cmds = [
    "cd backend",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python start.py"

[variables]
PYTHONUNBUFFERED = "1"
