[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"]

[phases.install]
cmds = [
    "echo '=== Python version ==='",
    "python --version || echo 'python not found'",
    "python3 --version || echo 'python3 not found'",
    "echo '=== Testing venv module ==='",
    "python -m venv --help > /dev/null && echo 'venv module is available' || echo 'venv module NOT available'",
    "echo '=== Creating virtual environment ==='",
    "python -m venv /opt/venv && echo 'venv created successfully' || echo 'venv creation FAILED'",
    "echo '=== Checking venv structure ==='",
    "ls -la /opt/venv/ || echo 'venv directory not found'",
    "echo '=== Testing pip in venv ==='",
    "/opt/venv/bin/python -m pip --version || echo 'pip not found in venv'",
    "echo '=== Installing minimal package ==='",
    "/opt/venv/bin/python -m pip install requests && echo 'requests installed successfully' || echo 'requests installation FAILED'",
    "echo '=== Installing from requirements.txt ==='",
    "/opt/venv/bin/python -m pip install -r requirements.txt -v"
]

[start]
cmd = "cd backend && python start.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
