[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"]

[phases.install]
cmds = [
    "python3.11 -m ensurepip",
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python3.11 backend/start.py"

[variables]
PYTHONUNBUFFERED = "1"
