[phases.setup]
nixPkgs = ["python311", "postgresql", "gcc"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/python -m pip install --upgrade pip",
    "/opt/venv/bin/python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python start.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
