[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
startCommand = "python start.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
name = "gymintel-backend-staging"
type = "web"

[services.gymintel-backend-staging]
port = 8000

[env]
ENVIRONMENT = "staging"
AUTO_INIT_DB = "true"
SEED_DATABASE = "true"
LOG_LEVEL = "DEBUG"
