name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci --prefer-offline

      - name: Run ESLint
        run: |
          cd frontend
          npm run lint || echo "ESLint failed but continuing..."
        continue-on-error: true

      - name: Run TypeScript type check
        run: |
          cd frontend
          npm run type-check || echo "TypeScript check failed but continuing..."
        continue-on-error: true

      - name: Run frontend tests
        run: |
          cd frontend
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ github.event_name }}" = "push" ]; then
            npm run test -- --coverage || echo "Tests failed but continuing..."
          else
            npm run test || echo "Tests failed but continuing..."
          fi
        continue-on-error: true

      - name: Upload frontend coverage to Codecov
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: codecov/codecov-action@v3
        with:
          files: ./frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_PASSWORD: testpass  # pragma: allowlist secret
          POSTGRES_USER: testuser
          POSTGRES_DB: test_gymintel
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run code formatting with Black
        run: |
          cd backend
          black .

      - name: Run import sorting with isort
        run: |
          cd backend
          isort .

      - name: Run linting (flake8)
        run: |
          cd backend
          flake8 . --max-line-length=88 --extend-ignore=E203,W503

      - name: Run backend tests
        env:
          TEST_DATABASE_HOST: localhost
          TEST_DATABASE_PORT: 5432
          TEST_DATABASE_NAME: test_gymintel
          TEST_DATABASE_USER: testuser
          TEST_DATABASE_PASSWORD: testpass  # pragma: allowlist secret
          ENVIRONMENT: testing
        run: |
          cd backend
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ github.event_name }}" = "push" ]; then
            pytest --cov=app --cov-report=xml
          else
            pytest -x  # Stop on first failure for faster feedback
          fi

      - name: Upload backend coverage to Codecov
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: codecov/codecov-action@v3
        with:
          files: ./backend/coverage.xml
          flags: backend
          name: backend-coverage

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [frontend-tests, backend-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: gymintel-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: gymintel-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [frontend-tests, backend-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        env:
          TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD || 'testpass' }}
          TEST_YELP_KEY: ${{ secrets.TEST_YELP_KEY || 'test-key' }}
          TEST_GOOGLE_KEY: ${{ secrets.TEST_GOOGLE_KEY || 'test-key' }}
          TEST_MAPBOX_TOKEN: ${{ secrets.TEST_MAPBOX_TOKEN || 'test-token' }}
        run: |
          cat > .env << EOF
          # Test environment variables
          DATABASE_HOST=database
          DATABASE_PORT=5432
          DATABASE_NAME=gymintel
          DATABASE_USER=postgres
          DATABASE_PASSWORD=${TEST_DB_PASSWORD}
          YELP_API_KEY=${TEST_YELP_KEY}
          GOOGLE_PLACES_API_KEY=${TEST_GOOGLE_KEY}
          MAPBOX_ACCESS_TOKEN=${TEST_MAPBOX_TOKEN}
          ENVIRONMENT=testing
          EOF

      - name: Start services with Docker Compose
        run: docker compose -f docker/docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 30

          # Check backend health
          curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost:8000/health

      - name: Run integration tests
        run: |
          # Test GraphQL endpoint
          curl -X POST http://localhost:8000/graphql \
            -H "Content-Type: application/json" \
            -d '{"query": "query { __typename }"}'

          # Test frontend is serving
          curl -f http://localhost:3000

      - name: Cleanup
        if: always()
        run: docker compose -f docker/docker-compose.yml down -v

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: 'trivy-results.sarif'
